### ISSUE TITLE
Stop using the sun package

### ISSUE THREAD

**Issue by JacobJBublitz** [SunnyBat/CommonCode#2]
Using the sun package is highly discouraged because the sun package is only guaranteed to be present in the oracle jvm. One way this could be avoided is to use [`java.util.Base64`](http://docs.oracle.com/javase/8/docs/api/java/util/Base64.html). However, using that class would mean that the project would only work with java 8.

More information on why not to use the sun package can be found [on oracle's website](http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html).

**Comment by SunnyBat** [comment]
I'd like to maintain compatibility with Java 7 for now. I haven't had any reports of this package causing issues, so for now I'm going to leave this be. If there's a small library/class (not something like Apache Commons, the codec binary alone is twice the size of CommonCode's binary) that can replace the use of the Sun package, definitely pull request it or reopen this with a link.
